CREATE TABLE IF NOT EXISTS armazens (
  id SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  nome VARCHAR(100) NOT NULL,
  codigo VARCHAR(20),
  descricao TEXT,
  endereco TEXT,
  "capacidadeTotal" DECIMAL(10,2),
  "unidadeCapacidade" VARCHAR(20) DEFAULT 'm²',
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "deletedAt" TIMESTAMP
);

ALTER TABLE produtos
  ADD COLUMN IF NOT EXISTS ean VARCHAR(20),
  ADD COLUMN IF NOT EXISTS marca VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "pesoUnitario" DECIMAL(8,3),
  ADD COLUMN IF NOT EXISTS "volumeUnitario" DECIMAL(8,3),
  ADD COLUMN IF NOT EXISTS "localizacaoPadrao" VARCHAR(30);

ALTER TABLE localizacoes
  ADD COLUMN IF NOT EXISTS corredor VARCHAR(10),
  ADD COLUMN IF NOT EXISTS bloco VARCHAR(10),
  ADD COLUMN IF NOT EXISTS prateleira VARCHAR(10),
  ADD COLUMN IF NOT EXISTS posicao VARCHAR(10),
  ADD COLUMN IF NOT EXISTS ativo BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE estoque
  ADD COLUMN IF NOT EXISTS "localizacaoId" INTEGER,
  ADD COLUMN IF NOT EXISTS lote VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "dataValidade" DATE;

ALTER TABLE movimentacoes_estoque
  ADD COLUMN IF NOT EXISTS "localizacaoOrigemId" INTEGER,
  ADD COLUMN IF NOT EXISTS "localizacaoDestinoId" INTEGER,
  ADD COLUMN IF NOT EXISTS "saldoAnterior" DECIMAL(12,3),
  ADD COLUMN IF NOT EXISTS "saldoAtual" DECIMAL(12,3),
  ADD COLUMN IF NOT EXISTS lote VARCHAR(50),
  ADD COLUMN IF NOT EXISTS documento VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "recebimentoId" INTEGER,
  ADD COLUMN IF NOT EXISTS observacoes TEXT,
  ADD COLUMN IF NOT EXISTS "operadorId" INTEGER;

ALTER TABLE carregamentos
  ADD COLUMN IF NOT EXISTS numero VARCHAR(20),
  ADD COLUMN IF NOT EXISTS data DATE,
  ADD COLUMN IF NOT EXISTS "veiculoPlaca" VARCHAR(10),
  ADD COLUMN IF NOT EXISTS "motoristaNome" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "ajudanteId" INTEGER,
  ADD COLUMN IF NOT EXISTS "ajudanteNome" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "rotaDescricao" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "cidadesRota" TEXT,
  ADD COLUMN IF NOT EXISTS "dataSaida" TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "dataRetorno" TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "kmSaida" INTEGER,
  ADD COLUMN IF NOT EXISTS "kmRetorno" INTEGER,
  ADD COLUMN IF NOT EXISTS "totalNfs" INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalVolumes" INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalPesoKg" DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalValorNfs" DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP;

ALTER TABLE itens_carregamento
  ADD COLUMN IF NOT EXISTS "empresaId" INTEGER,
  ADD COLUMN IF NOT EXISTS "numeroNf" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS serie VARCHAR(10),
  ADD COLUMN IF NOT EXISTS "chaveAcesso" VARCHAR(60),
  ADD COLUMN IF NOT EXISTS destinatario VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "cnpjDestinatario" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "enderecoEntrega" TEXT,
  ADD COLUMN IF NOT EXISTS cidade VARCHAR(100),
  ADD COLUMN IF NOT EXISTS uf VARCHAR(2),
  ADD COLUMN IF NOT EXISTS "valorNf" DECIMAL(12,2),
  ADD COLUMN IF NOT EXISTS "pesoKg" DECIMAL(10,3),
  ADD COLUMN IF NOT EXISTS volumes INTEGER,
  ADD COLUMN IF NOT EXISTS "descricaoCarga" TEXT,
  ADD COLUMN IF NOT EXISTS "ordemEntrega" INTEGER,
  ADD COLUMN IF NOT EXISTS observacoes TEXT,
  ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'pendente',
  ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW();

UPDATE carregamentos
SET data = COALESCE(data, CURRENT_DATE),
    numero = COALESCE(numero, CONCAT('CARG-', LPAD(id::TEXT, 4, '0')))
WHERE data IS NULL OR numero IS NULL;

UPDATE itens_carregamento
SET "empresaId" = c."empresaId"
FROM carregamentos c
WHERE itens_carregamento."empresaId" IS NULL
  AND c.id = itens_carregamento."carregamentoId";

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_indexes
    WHERE schemaname = 'public'
      AND indexname = 'estoque_empresa_produto_armazem_uidx'
  ) THEN
    EXECUTE 'CREATE UNIQUE INDEX estoque_empresa_produto_armazem_uidx ON estoque ("empresaId","produtoId","armazemId")';
  END IF;
END $$;
