// AUTO-GENERATED: inline migrations for Railway deployment
// All SQL is embedded here so no external files are needed

import { getRawClient } from "./db";

const MIGRATION_STATEMENTS: string[] = [
  `CREATE TYPE "public"."categoria_conta_pagar" AS ENUM('combustivel', 'manutencao', 'salario', 'freelancer', 'pedagio', 'seguro', 'ipva', 'licenciamento', 'pneu', 'outro')`,
  `CREATE TYPE "public"."categoria_conta_receber" AS ENUM('frete', 'cte', 'devolucao', 'outro')`,
  `CREATE TYPE "public"."chat_message_type" AS ENUM('text', 'image', 'file')`,
  `CREATE TYPE "public"."chat_role" AS ENUM('admin', 'member')`,
  `CREATE TYPE "public"."forma_pagamento" AS ENUM('dinheiro', 'pix', 'transferencia', 'cartao')`,
  `CREATE TYPE "public"."funcao" AS ENUM('motorista', 'ajudante', 'despachante', 'gerente', 'admin', 'outro')`,
  `CREATE TYPE "public"."item_checklist" AS ENUM('conforme', 'nao_conforme', 'na')`,
  `CREATE TYPE "public"."operacao_tanque" AS ENUM('entrada', 'saida')`,
  `CREATE TYPE "public"."status_acidente" AS ENUM('aberto', 'em_reparo', 'resolvido')`,
  `CREATE TYPE "public"."status_adiantamento" AS ENUM('pendente', 'acertado', 'cancelado')`,
  `CREATE TYPE "public"."status_conta_pagar" AS ENUM('pendente', 'pago', 'vencido', 'cancelado')`,
  `CREATE TYPE "public"."status_conta_receber" AS ENUM('pendente', 'recebido', 'vencido', 'cancelado')`,
  `CREATE TYPE "public"."status_viagem" AS ENUM('planejada', 'em_andamento', 'concluida', 'cancelada')`,
  `CREATE TYPE "public"."tipo_abastecimento" AS ENUM('interno', 'externo')`,
  `CREATE TYPE "public"."tipo_checklist" AS ENUM('saida', 'retorno')`,
  `CREATE TYPE "public"."tipo_cobranca" AS ENUM('diaria', 'mensal', 'por_viagem')`,
  `CREATE TYPE "public"."tipo_combustivel" AS ENUM('diesel', 'arla', 'gasolina', 'etanol', 'gas', 'outro')`,
  `CREATE TYPE "public"."tipo_conta" AS ENUM('corrente', 'poupanca', 'pix')`,
  `CREATE TYPE "public"."tipo_contrato" AS ENUM('clt', 'freelancer', 'terceirizado', 'estagiario')`,
  `CREATE TYPE "public"."tipo_despesa" AS ENUM('combustivel', 'pedagio', 'borracharia', 'estacionamento', 'oficina', 'telefone', 'descarga', 'diaria', 'alimentacao', 'outro')`,
  `CREATE TYPE "public"."tipo_manutencao" AS ENUM('preventiva', 'corretiva', 'revisao', 'pneu', 'eletrica', 'funilaria', 'outro')`,
  `CREATE TYPE "public"."tipo_tanque" AS ENUM('diesel', 'arla')`,
  `CREATE TYPE "public"."tipo_veiculo" AS ENUM('van', 'toco', 'truck', 'cavalo', 'carreta', 'empilhadeira', 'paletera', 'outro')`,
  `CREATE TYPE "public"."tipo_viagem" AS ENUM('entrega', 'viagem')`,
  `CREATE TYPE "public"."turno" AS ENUM('manha', 'tarde', 'noite')`,
  `CREATE TYPE "public"."user_role" AS ENUM('user', 'admin', 'master_admin', 'monitor', 'dispatcher')`,
  `CREATE TABLE "abastecimentos" (
	"id" serial PRIMARY KEY NOT NULL,
	"empresaId" integer NOT NULL,
	"veiculoId" integer NOT NULL,
	"motoristaId" integer,
	"data" date NOT NULL,
	"tipoCombustivel" "tipo_combustivel" NOT NULL,
	"quantidade" numeric(8, 3) NOT NULL,
	"valorUnitario" numeric(8, 3),
	"valorTotal" numeric(10, 2),
	"kmAtual" integer,
	"kmRodado" integer,
	"mediaConsumo" numeric(5, 2),
	"local" varchar(255),
	"tipoAbastecimento" "tipo_abastecimento" DEFAULT 'interno',
	"notaFiscal" varchar(50),
	"observacoes" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"deletedBy" integer,
	"deleteReason" text
)`,
  `CREATE TABLE "acidentes" (
	"id" serial PRIMARY KEY NOT NULL,
	"empresaId" integer NOT NULL,
	"veiculoId" integer NOT NULL,
	"motoristaId" integer,
	"data" date NOT NULL,
	"local" varchar(255),
	"descricao" text NOT NULL,
	"boletimOcorrencia" varchar(50),
	"valorDano" numeric(10, 2),
	"status" "status_acidente" DEFAULT 'aberto' NOT NULL,
	"observacoes" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"deletedBy" integer,
	"deleteReason" text
)`,
  `CREATE TABLE "adiantamentos" (
	"id" serial PRIMARY KEY NOT NULL,
	"empresaId" integer NOT NULL,
	"funcionarioId" integer NOT NULL,
	"viagemId" integer,
	"valor" numeric(10, 2) NOT NULL,
	"formaPagamento" "forma_pagamento" NOT NULL,
	"data" date NOT NULL,
	"status" "status_adiantamento" DEFAULT 'pendente' NOT NULL,
	"valorAcertado" numeric(10, 2),
	"dataAcerto" date,
	"saldo" numeric(10, 2),
	"observacoes" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"deletedBy" integer,
	"deleteReason" text
)`,
  `CREATE TABLE "audit_log" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"empresaId" integer,
	"userId" integer NOT NULL,
	"userName" varchar(255),
	"acao" varchar(50) NOT NULL,
	"tabela" varchar(100) NOT NULL,
	"registroId" integer NOT NULL,
	"dadosAntes" text,
	"dadosDepois" text,
	"ip" varchar(45),
	"userAgent" text,
	"createdAt" timestamp DEFAULT now() NOT NULL
)`,
  `CREATE TABLE "chat_conversations" (
	"id" serial PRIMARY KEY NOT NULL,
	"empresaId" integer NOT NULL,
	"name" varchar(255),
	"isGroup" boolean DEFAULT false NOT NULL,
	"lastMessageAt" timestamp DEFAULT now() NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp
)`,
  `CREATE TABLE "chat_members" (
	"id" serial PRIMARY KEY NOT NULL,
	"conversationId" integer NOT NULL,
	"userId" integer NOT NULL,
	"role" "chat_role" DEFAULT 'member' NOT NULL,
	"joinedAt" timestamp DEFAULT now() NOT NULL,
	"lastReadAt" timestamp DEFAULT now() NOT NULL
)`,
  `CREATE TABLE "chat_messages" (
	"id" serial PRIMARY KEY NOT NULL,
	"conversationId" integer NOT NULL,
	"senderId" integer NOT NULL,
	"content" text NOT NULL,
	"type" "chat_message_type" DEFAULT 'text' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp
)`,
  `CREATE TABLE "checklists" (
	"id" serial PRIMARY KEY NOT NULL,
	"empresaId" integer NOT NULL,
	"veiculoId" integer NOT NULL,
	"cavaloPrincipalId" integer,
	"motoristaId" integer,
	"turno" "turno",
	"tipo" "tipo_checklist" DEFAULT 'retorno' NOT NULL,
	"cracha" "item_checklist",
	"cnh" "item_checklist",
	"documentosVeiculo" "item_checklist",
	"epi" "item_checklist",
	"computadorBordo" "item_checklist",
	"cinto" "item_checklist",
	"banco" "item_checklist",
	"direcao" "item_checklist",
	"luzesPainel" "item_checklist",
	"tacografo" "item_checklist",
	"extintor" "item_checklist",
	"portas" "item_checklist",
	"limpador" "item_checklist",
	"buzina" "item_checklist",
	"freioDeMao" "item_checklist",
	"alarmeCacamba" "item_checklist",
	"cabineLimpa" "item_checklist",
	"objetosSoltos" "item_checklist",
	"pneus" "item_checklist",
	"vazamentos" "item_checklist",
	"trianguloCones" "item_checklist",
	"espelhos" "item_checklist",
	"lonaCarga" "item_checklist",
	"faixasRefletivas" "item_checklist",
	"luzesLaterais" "item_checklist",
	"luzesFreio" "item_checklist",
	"farol" "item_checklist",
	"piscaAlerta" "item_checklist",
	"re" "item_checklist",
	"setas" "item_checklist",
	"macacoEstepe" "item_checklist",
	"lanternas" "item_checklist",
	"itensNaoConformes" integer DEFAULT 0,
	"observacoes" text,
	"assinaturaMotorista" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"deletedBy" integer,
	"deleteReason" text
)`,
  `CREATE TABLE "contas_pagar" (
	"id" serial PRIMARY KEY NOT NULL,
	"empresaId" integer NOT NULL,
	"descricao" text NOT NULL,
	"categoria" "categoria_conta_pagar" NOT NULL,
	"valor" numeric(10, 2) NOT NULL,
	"dataVencimento" date NOT NULL,
	"dataPagamento" date,
	"status" "status_conta_pagar" DEFAULT 'pendente' NOT NULL,
	"fornecedor" varchar(255),
	"notaFiscal" varchar(50),
	"veiculoId" integer,
	"funcionarioId" integer,
	"viagemId" integer,
	"comprovante" text,
	"observacoes" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"deletedBy" integer,
	"deleteReason" text
)`,
  `CREATE TABLE "contas_receber" (
	"id" serial PRIMARY KEY NOT NULL,
	"empresaId" integer NOT NULL,
	"descricao" text NOT NULL,
	"categoria" "categoria_conta_receber" NOT NULL,
	"valor" numeric(10, 2) NOT NULL,
	"dataVencimento" date NOT NULL,
	"dataRecebimento" date,
	"status" "status_conta_receber" DEFAULT 'pendente' NOT NULL,
	"cliente" varchar(255),
	"notaFiscal" varchar(50),
	"cteNumero" varchar(50),
	"viagemId" integer,
	"observacoes" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"deletedBy" integer,
	"deleteReason" text
)`,
  `CREATE TABLE "controle_tanque" (
	"id" serial PRIMARY KEY NOT NULL,
	"empresaId" integer NOT NULL,
	"tipo" "tipo_tanque" NOT NULL,
	"data" date NOT NULL,
	"operacao" "operacao_tanque" NOT NULL,
	"quantidade" numeric(8, 3) NOT NULL,
	"valorUnitario" numeric(8, 3),
	"valorTotal" numeric(10, 2),
	"fornecedor" varchar(255),
	"notaFiscal" varchar(50),
	"veiculoId" integer,
	"motoristaId" integer,
	"saldoAnterior" numeric(8, 3),
	"saldoAtual" numeric(8, 3),
	"observacoes" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"deletedBy" integer,
	"deleteReason" text
)`,
  `CREATE TABLE "despesas_viagem" (
	"id" serial PRIMARY KEY NOT NULL,
	"viagemId" integer NOT NULL,
	"empresaId" integer NOT NULL,
	"tipo" "tipo_despesa" NOT NULL,
	"descricao" text,
	"valor" numeric(10, 2) NOT NULL,
	"data" date,
	"comprovante" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"deletedBy" integer,
	"deleteReason" text
)`,
  `CREATE TABLE "empresas" (
	"id" serial PRIMARY KEY NOT NULL,
	"nome" varchar(255) NOT NULL,
	"cnpj" varchar(18),
	"telefone" varchar(20),
	"email" varchar(320),
	"endereco" text,
	"cidade" varchar(100),
	"estado" varchar(2),
	"ativo" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"deletedBy" integer,
	"deleteReason" text
)`,
  `CREATE TABLE "funcionarios" (
	"id" serial PRIMARY KEY NOT NULL,
	"empresaId" integer NOT NULL,
	"nome" varchar(255) NOT NULL,
	"cpf" varchar(14),
	"rg" varchar(20),
	"telefone" varchar(20),
	"email" varchar(320),
	"funcao" "funcao" NOT NULL,
	"tipoContrato" "tipo_contrato" NOT NULL,
	"salario" numeric(10, 2),
	"dataAdmissao" date,
	"dataDemissao" date,
	"valorDiaria" numeric(10, 2),
	"valorMensal" numeric(10, 2),
	"tipoCobranca" "tipo_cobranca",
	"dataInicioContrato" date,
	"dataFimContrato" date,
	"diaPagamento" integer,
	"cnh" varchar(20),
	"categoriaCnh" varchar(5),
	"vencimentoCnh" date,
	"mopp" boolean DEFAULT false,
	"vencimentoMopp" date,
	"vencimentoAso" date,
	"banco" varchar(100),
	"agencia" varchar(10),
	"conta" varchar(20),
	"tipoConta" "tipo_conta",
	"chavePix" varchar(255),
	"observacoes" text,
	"foto" text,
	"ativo" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"deletedBy" integer,
	"deleteReason" text
)`,
  `CREATE TABLE "manutencoes" (
	"id" serial PRIMARY KEY NOT NULL,
	"empresaId" integer NOT NULL,
	"veiculoId" integer NOT NULL,
	"data" date NOT NULL,
	"tipo" "tipo_manutencao" NOT NULL,
	"descricao" text NOT NULL,
	"empresa" varchar(255),
	"valor" numeric(10, 2),
	"kmAtual" integer,
	"proximaManutencaoKm" integer,
	"proximaManutencaoData" date,
	"notaFiscal" varchar(50),
	"observacoes" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"deletedBy" integer,
	"deleteReason" text
)`,
  `CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"openId" varchar(64) NOT NULL,
	"name" text,
	"email" varchar(320),
	"loginMethod" varchar(64),
	"password" varchar(255),
	"role" "user_role" DEFAULT 'user' NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_openId_unique" UNIQUE("openId")
)`,
  `CREATE TABLE "veiculos" (
	"id" serial PRIMARY KEY NOT NULL,
	"empresaId" integer NOT NULL,
	"placa" varchar(10) NOT NULL,
	"tipo" "tipo_veiculo" NOT NULL,
	"cavaloPrincipalId" integer,
	"marca" varchar(100),
	"modelo" varchar(100),
	"ano" integer,
	"cor" varchar(50),
	"renavam" varchar(20),
	"chassi" varchar(30),
	"capacidadeCarga" numeric(8, 2),
	"motoristaId" integer,
	"ajudanteId" integer,
	"kmAtual" integer,
	"mediaConsumo" numeric(5, 2),
	"vencimentoCrlv" date,
	"vencimentoSeguro" date,
	"classificacao" integer DEFAULT 0,
	"observacoes" text,
	"ativo" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"deletedBy" integer,
	"deleteReason" text
)`,
  `CREATE TABLE "viagens" (
	"id" serial PRIMARY KEY NOT NULL,
	"empresaId" integer NOT NULL,
	"tipo" "tipo_viagem" DEFAULT 'viagem' NOT NULL,
	"veiculoId" integer NOT NULL,
	"cavaloPrincipalId" integer,
	"motoristaId" integer,
	"ajudante1Id" integer,
	"ajudante2Id" integer,
	"ajudante3Id" integer,
	"origem" varchar(255),
	"destino" varchar(255),
	"dataSaida" timestamp,
	"dataChegada" timestamp,
	"kmSaida" integer,
	"kmChegada" integer,
	"kmRodado" integer,
	"descricaoCarga" text,
	"tipoCarga" text,
	"pesoCarga" numeric(8, 2),
	"freteTotalIda" numeric(10, 2),
	"freteTotalVolta" numeric(10, 2),
	"freteTotal" numeric(10, 2),
	"adiantamento" numeric(10, 2),
	"saldoViagem" numeric(10, 2),
	"totalDespesas" numeric(10, 2),
	"mediaConsumo" numeric(5, 2),
	"notaFiscal" varchar(50),
	"status" "status_viagem" DEFAULT 'planejada' NOT NULL,
	"observacoes" text,
	"teveProblema" boolean DEFAULT false,
	"voltouComCarga" boolean DEFAULT false,
	"observacoesChegada" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"deletedBy" integer,
	"deleteReason" text
)`,
  `CREATE TABLE IF NOT EXISTS "notas_fiscais_viagem" (
  "id"                SERIAL PRIMARY KEY,
  "empresaId"         INTEGER NOT NULL,
  "viagemId"          INTEGER NOT NULL,
  "numeroNf"          VARCHAR(20) NOT NULL,
  "serie"             VARCHAR(5),
  "chaveAcesso"       VARCHAR(44),
  "destinatario"      VARCHAR(255),
  "cnpjDestinatario"  VARCHAR(18),
  "enderecoEntrega"   VARCHAR(500),
  "cidade"            VARCHAR(100),
  "uf"                VARCHAR(2),
  "valorNf"           DECIMAL(12, 2),
  "pesoKg"            DECIMAL(8, 2),
  "volumes"           INTEGER,
  "status"            "status_nf" NOT NULL DEFAULT 'pendente',
  "dataCanhoto"       TIMESTAMP,
  "dataEntrega"       TIMESTAMP,
  "recebidoPor"       VARCHAR(255),
  "motivoDevolucao"   TEXT,
  "observacoes"       TEXT,
  "ordemEntrega"      INTEGER,
  "createdAt"         TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt"         TIMESTAMP NOT NULL DEFAULT NOW(),
  "deletedAt"         TIMESTAMP
)`,
  `CREATE INDEX IF NOT EXISTS "idx_nfv_viagem" ON "notas_fiscais_viagem" ("viagemId")`,
  `CREATE INDEX IF NOT EXISTS "idx_nfv_empresa" ON "notas_fiscais_viagem" ("empresaId")`,
  `CREATE INDEX IF NOT EXISTS "idx_nfv_numero" ON "notas_fiscais_viagem" ("numeroNf")`,
  `ALTER TABLE empresas ADD COLUMN matrizId INTEGER`,
  `CREATE TYPE "status_pneu" AS ENUM('novo', 'em_uso', 'recapado', 'sucata', 'estoque')`,
  `CREATE TABLE IF NOT EXISTS "pneus" (
"id" serial PRIMARY KEY NOT NULL,
"empresaId" integer NOT NULL,
"numeroSerie" varchar(50) NOT NULL,
"marca" varchar(100),
"modelo" varchar(100),
"medida" varchar(50),
"kmInicial" integer DEFAULT 0,
"kmAtual" integer DEFAULT 0,
"status" "status_pneu" DEFAULT 'novo' NOT NULL,
"veiculoId" integer,
"posicao" varchar(50),
"dataAquisicao" date,
"valorAquisicao" numeric(10, 2),
"observacoes" text,
"createdAt" timestamp DEFAULT now() NOT NULL,
"updatedAt" timestamp DEFAULT now() NOT NULL,
"deletedAt" timestamp,
"deletedBy" integer,
"deleteReason" text
)`,
  `CREATE TABLE IF NOT EXISTS "historico_pneus" (
"id" serial PRIMARY KEY NOT NULL,
"empresaId" integer NOT NULL,
"pneuId" integer NOT NULL,
"data" timestamp DEFAULT now() NOT NULL,
"tipo" varchar(50) NOT NULL,
"veiculoId" integer,
"posicao" varchar(50),
"kmVeiculo" integer,
"kmPneu" integer,
"custo" numeric(10, 2),
"observacoes" text,
"createdAt" timestamp DEFAULT now() NOT NULL
)`,
  `CREATE TYPE "tipo_documento" AS ENUM('cnh', 'crlv', 'aso', 'mopp', 'nota_fiscais', 'seguro', 'licenciamento', 'contrato', 'outro')`,
  `CREATE TABLE IF NOT EXISTS "documentos" (
"id" serial PRIMARY KEY NOT NULL,
"empresaId" integer NOT NULL,
"tipo" "tipo_documento" NOT NULL,
"nome" varchar(255) NOT NULL,
"url" text NOT NULL,
"extensao" varchar(10),
"tamanho" integer,
"veiculoId" integer,
"funcionarioId" integer,
"viagemId" integer,
"manutencaoId" integer,
"dataVencimento" date,
"observacoes" text,
"createdAt" timestamp DEFAULT now() NOT NULL,
"updatedAt" timestamp DEFAULT now() NOT NULL,
"deletedAt" timestamp,
"deletedBy" integer
)`,
  `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "phone" varchar(20)`,
  `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "empresaId" integer`,
  `DO $$ BEGIN
  CREATE TYPE "ciclo_cobranca" AS ENUM ('mensal','trimestral','semestral','anual');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "forma_pagamento_saas" AS ENUM ('cartao_credito','boleto','pix','transferencia');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "ia_agente_setor" AS ENUM ('master','financeiro','frota','motorista','manutencao','juridico','recepcao','wms','rh','ti','comercial','marketing');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "plano_cod" AS ENUM ('starter','professional','enterprise','custom');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "prioridade_sac" AS ENUM ('baixa','media','alta','urgente');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "categoria_ticket_ti" AS ENUM ('hardware','software','rede','acesso','email','impressora','outro');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "prioridade_ticket_ti" AS ENUM ('baixa','media','alta','critica');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "status_acerto_carga" AS ENUM ('pendente','em_analise','aprovado','rejeitado','cancelado');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "status_carregamento" AS ENUM ('planejado','em_carregamento','carregado','em_transito','entregue','cancelado');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "status_cobranca" AS ENUM ('pendente','pago','atrasado','cancelado','estornado');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "status_conferencia" AS ENUM ('saida_registrada','em_viagem','retorno_registrado','em_conferencia','aguardando_motorista','confirmado_motorista','finalizado');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "status_integracao" AS ENUM ('ativa','inativa','erro','configurando');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "status_item_recebimento" AS ENUM ('pendente','conferido','divergente','recusado');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "status_lead" AS ENUM ('novo','contatado','qualificado','proposta','negociacao','ganho','perdido','inativo');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "status_licenca" AS ENUM ('ativa','suspensa','cancelada','trial','expirada');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "status_licenca_log" AS ENUM ('ativada','suspensa','cancelada','reativada','atualizada','expirada');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "status_pedido" AS ENUM ('rascunho','enviado','aprovado','em_separacao','expedido','entregue','cancelado');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "status_proposta" AS ENUM ('rascunho','enviada','em_analise','aprovada','rejeitada','expirada');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "status_recebimento" AS ENUM ('agendado','em_andamento','concluido','divergente','cancelado');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "status_sac" AS ENUM ('aberto','em_andamento','aguardando_cliente','resolvido','fechado','reaberto');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "status_ticket_ti" AS ENUM ('aberto','em_andamento','aguardando','resolvido','fechado');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "status_visitante" AS ENUM ('aguardando','em_visita','finalizado','cancelado');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "tipo_empresa" AS ENUM ('matriz','filial','grupo','franquia','parceiro');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "tipo_evento_auditoria" AS ENUM ('login','logout','create','update','delete','restore','export','import','permission_change','config_change','access_denied','password_change','role_change');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "tipo_movimentacao_estoque" AS ENUM ('entrada','saida','transferencia','ajuste','inventario','devolucao','perda');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "tipo_ponto" AS ENUM ('entrada','saida','inicio_intervalo','fim_intervalo');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `DO $$ BEGIN
  CREATE TYPE "tipo_recebimento" AS ENUM ('compra','devolucao','transferencia','bonificacao');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$`,
  `CREATE TABLE IF NOT EXISTS "grupo_empresas" (
  "id" SERIAL PRIMARY KEY,
  "grupoId" INTEGER NOT NULL,
  "empresaId" INTEGER NOT NULL,
  "papel" VARCHAR(20) NOT NULL DEFAULT 'filial',
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "licencas" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "planoId" INTEGER,
  "status" "status_licenca" NOT NULL DEFAULT 'trial',
  "dataInicio" TIMESTAMP NOT NULL DEFAULT NOW(),
  "dataFim" TIMESTAMP,
  "trialAte" TIMESTAMP,
  "usuariosAtivos" INTEGER DEFAULT 0,
  "limiteUsuarios" INTEGER DEFAULT 5,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "cobrancas" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "licencaId" INTEGER,
  "valor" VARCHAR(20) NOT NULL,
  "status" "status_cobranca" NOT NULL DEFAULT 'pendente',
  "formaPagamento" "forma_pagamento_saas",
  "vencimento" TIMESTAMP,
  "pago" BOOLEAN NOT NULL DEFAULT FALSE,
  "dataPagamento" TIMESTAMP,
  "referencia" VARCHAR(100),
  "linkPagamento" TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "licencas_regulatorias" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "tipo" VARCHAR(100) NOT NULL,
  "numero" VARCHAR(100),
  "orgaoEmissor" VARCHAR(100),
  "dataEmissao" TIMESTAMP,
  "dataVencimento" TIMESTAMP,
  "status" "status_licenca" NOT NULL DEFAULT 'ativa',
  "arquivo" TEXT,
  "observacoes" TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "user_permissoes" (
  "id" SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "empresaId" INTEGER NOT NULL,
  "modulo" VARCHAR(100) NOT NULL,
  "podeVer" BOOLEAN NOT NULL DEFAULT FALSE,
  "podeCriar" BOOLEAN NOT NULL DEFAULT FALSE,
  "podeEditar" BOOLEAN NOT NULL DEFAULT FALSE,
  "podeDeletar" BOOLEAN NOT NULL DEFAULT FALSE,
  "podeExportar" BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "etapas_funil" (
  "id" SERIAL PRIMARY KEY,
  "funilId" INTEGER NOT NULL,
  "empresaId" INTEGER NOT NULL,
  "nome" VARCHAR(255) NOT NULL,
  "cor" VARCHAR(20) DEFAULT '#3b82f6',
  "posicao" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "negociacoes" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "funilId" INTEGER NOT NULL,
  "etapaId" INTEGER NOT NULL,
  "clienteId" INTEGER,
  "leadId" INTEGER,
  "titulo" VARCHAR(255) NOT NULL,
  "valor" VARCHAR(20) DEFAULT '0',
  "responsavelId" INTEGER,
  "probabilidade" INTEGER DEFAULT 50,
  "previsaoFechamento" TIMESTAMP,
  "motivoPerda" TEXT,
  "ganho" BOOLEAN,
  "observacoes" TEXT,
  "createdBy" INTEGER,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "deletedAt" TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS "atividades_funil" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "negociacaoId" INTEGER NOT NULL,
  "tipo" VARCHAR(50) NOT NULL,
  "titulo" VARCHAR(255) NOT NULL,
  "descricao" TEXT,
  "dataAgendada" TIMESTAMP,
  "concluida" BOOLEAN NOT NULL DEFAULT FALSE,
  "userId" INTEGER,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "itens_pedido" (
  "id" SERIAL PRIMARY KEY,
  "pedidoId" INTEGER NOT NULL,
  "produtoId" INTEGER,
  "descricao" VARCHAR(255) NOT NULL,
  "quantidade" VARCHAR(20) NOT NULL,
  "valorUnitario" VARCHAR(20) NOT NULL,
  "valorTotal" VARCHAR(20) NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "propostas" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "clienteId" INTEGER,
  "leadId" INTEGER,
  "numero" VARCHAR(30) NOT NULL,
  "titulo" VARCHAR(255) NOT NULL,
  "status" "status_proposta" NOT NULL DEFAULT 'rascunho',
  "valorTotal" VARCHAR(20) DEFAULT '0',
  "validade" TIMESTAMP,
  "descricao" TEXT,
  "condicoes" TEXT,
  "vendedorId" INTEGER,
  "createdBy" INTEGER,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "deletedAt" TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS "comissoes" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "vendedorId" INTEGER NOT NULL,
  "pedidoId" INTEGER,
  "percentual" VARCHAR(10) NOT NULL,
  "valorBase" VARCHAR(20) NOT NULL,
  "valorComissao" VARCHAR(20) NOT NULL,
  "pago" BOOLEAN NOT NULL DEFAULT FALSE,
  "dataPagamento" TIMESTAMP,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "docas" (
  "id" SERIAL PRIMARY KEY,
  "armazemId" INTEGER NOT NULL,
  "empresaId" INTEGER NOT NULL,
  "nome" VARCHAR(100) NOT NULL,
  "tipo" VARCHAR(50) DEFAULT 'recebimento',
  "status" VARCHAR(50) DEFAULT 'livre',
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "produtos" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "codigo" VARCHAR(100) NOT NULL,
  "codigoBarras" VARCHAR(100),
  "nome" VARCHAR(255) NOT NULL,
  "descricao" TEXT,
  "categoria" VARCHAR(100),
  "unidade" VARCHAR(20) DEFAULT 'UN',
  "pesoKg" VARCHAR(20),
  "volumeM3" VARCHAR(20),
  "valorCusto" VARCHAR(20),
  "valorVenda" VARCHAR(20),
  "estoqueMinimo" INTEGER DEFAULT 0,
  "estoqueMaximo" INTEGER,
  "ativo" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "deletedAt" TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS "estoque" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "armazemId" INTEGER NOT NULL,
  "produtoId" INTEGER NOT NULL,
  "quantidade" INTEGER NOT NULL DEFAULT 0,
  "quantidadeReservada" INTEGER NOT NULL DEFAULT 0,
  "localizacao" VARCHAR(100),
  "lote" VARCHAR(100),
  "dataValidade" TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "movimentacoes_estoque" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "armazemId" INTEGER NOT NULL,
  "produtoId" INTEGER NOT NULL,
  "tipo" "tipo_movimentacao_estoque" NOT NULL,
  "quantidade" INTEGER NOT NULL,
  "quantidadeAntes" INTEGER NOT NULL DEFAULT 0,
  "quantidadeDepois" INTEGER NOT NULL DEFAULT 0,
  "motivo" TEXT,
  "documentoRef" VARCHAR(100),
  "userId" INTEGER,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "localizacoes" (
  "id" SERIAL PRIMARY KEY,
  "armazemId" INTEGER NOT NULL,
  "empresaId" INTEGER NOT NULL,
  "rua" VARCHAR(20),
  "bloco" VARCHAR(20),
  "nivel" VARCHAR(20),
  "posicao" VARCHAR(20),
  "codigo" VARCHAR(50) NOT NULL,
  "tipo" VARCHAR(50) DEFAULT 'padrao',
  "capacidade" INTEGER,
  "ocupado" BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "recebimentos" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "armazemId" INTEGER NOT NULL,
  "docaId" INTEGER,
  "tipo" "tipo_recebimento" NOT NULL DEFAULT 'compra',
  "status" "status_recebimento" NOT NULL DEFAULT 'agendado',
  "fornecedor" VARCHAR(255),
  "notaFiscal" VARCHAR(100),
  "dataAgendada" TIMESTAMP,
  "dataInicio" TIMESTAMP,
  "dataConclusao" TIMESTAMP,
  "responsavelId" INTEGER,
  "observacoes" TEXT,
  "createdBy" INTEGER,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "itens_recebimento" (
  "id" SERIAL PRIMARY KEY,
  "recebimentoId" INTEGER NOT NULL,
  "produtoId" INTEGER,
  "descricao" VARCHAR(255) NOT NULL,
  "quantidadeEsperada" INTEGER NOT NULL,
  "quantidadeRecebida" INTEGER DEFAULT 0,
  "status" "status_item_recebimento" NOT NULL DEFAULT 'pendente',
  "observacoes" TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "carregamentos" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "armazemId" INTEGER NOT NULL,
  "docaId" INTEGER,
  "status" "status_carregamento" NOT NULL DEFAULT 'planejado',
  "veiculoId" INTEGER,
  "motoristaId" INTEGER,
  "dataAgendada" TIMESTAMP,
  "dataInicio" TIMESTAMP,
  "dataConclusao" TIMESTAMP,
  "responsavelId" INTEGER,
  "observacoes" TEXT,
  "createdBy" INTEGER,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "itens_carregamento" (
  "id" SERIAL PRIMARY KEY,
  "carregamentoId" INTEGER NOT NULL,
  "produtoId" INTEGER,
  "descricao" VARCHAR(255) NOT NULL,
  "quantidade" INTEGER NOT NULL,
  "quantidadeCarregada" INTEGER DEFAULT 0,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "acertos_carga" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "carregamentoId" INTEGER,
  "motoristaId" INTEGER,
  "status" "status_acerto_carga" NOT NULL DEFAULT 'pendente',
  "valorAdiantado" VARCHAR(20),
  "valorDespesas" VARCHAR(20),
  "comprovantes" TEXT,
  "observacoes" TEXT,
  "aprovadoPor" INTEGER,
  "createdBy" INTEGER,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "ativos_ti" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "tipo" VARCHAR(100) NOT NULL,
  "marca" VARCHAR(100),
  "modelo" VARCHAR(100),
  "patrimonio" VARCHAR(50),
  "serial" VARCHAR(100),
  "responsavelId" INTEGER,
  "setor" VARCHAR(100),
  "status" VARCHAR(50) NOT NULL DEFAULT 'ativo',
  "dataAquisicao" TIMESTAMP,
  "garantiaAte" TIMESTAMP,
  "observacoes" TEXT,
  "anydesk" VARCHAR(50),
  "sistemaOperacional" VARCHAR(100),
  "processador" VARCHAR(100),
  "memoriaRam" VARCHAR(50),
  "armazenamento" VARCHAR(100),
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "deletedAt" TIMESTAMP
)`,
  `CREATE TABLE IF NOT EXISTS "bi_widgets" (
  "id" SERIAL PRIMARY KEY,
  "dashboardId" INTEGER NOT NULL,
  "empresaId" INTEGER NOT NULL,
  "titulo" VARCHAR(255) NOT NULL,
  "tipo" VARCHAR(50) NOT NULL,
  "fonte" VARCHAR(100) NOT NULL,
  "metrica" VARCHAR(100) NOT NULL,
  "filtros" TEXT,
  "posicao" INTEGER DEFAULT 0,
  "largura" INTEGER DEFAULT 6,
  "altura" INTEGER DEFAULT 4,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "ia_sessoes" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "userId" INTEGER NOT NULL,
  "agenteId" INTEGER,
  "titulo" VARCHAR(255),
  "ativa" BOOLEAN NOT NULL DEFAULT TRUE,
  "totalMensagens" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "ia_mensagens" (
  "id" SERIAL PRIMARY KEY,
  "sessaoId" INTEGER NOT NULL,
  "empresaId" INTEGER NOT NULL,
  "role" VARCHAR(20) NOT NULL DEFAULT 'user',
  "content" TEXT NOT NULL,
  "tokens" INTEGER,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "ia_conhecimento" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "titulo" VARCHAR(255) NOT NULL,
  "conteudo" TEXT NOT NULL,
  "categoria" VARCHAR(100),
  "tags" TEXT,
  "ativo" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdBy" INTEGER,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "log_integracoes" (
  "id" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "integracaoId" INTEGER NOT NULL,
  "empresaId" INTEGER NOT NULL,
  "direcao" VARCHAR(10) NOT NULL,
  "endpoint" VARCHAR(500),
  "payload" TEXT,
  "resposta" TEXT,
  "statusCode" INTEGER,
  "sucesso" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "winthor_sync" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "integracaoId" INTEGER NOT NULL,
  "tabelaOrigem" VARCHAR(100) NOT NULL,
  "tabelaDestino" VARCHAR(100) NOT NULL,
  "ultimoId" INTEGER DEFAULT 0,
  "ultimaSincronizacao" TIMESTAMP,
  "registrosSincronizados" INTEGER DEFAULT 0,
  "ativo" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "visitas" (
  "id" SERIAL PRIMARY KEY,
  "visitanteId" INTEGER NOT NULL,
  "empresaId" INTEGER NOT NULL,
  "entrada" TIMESTAMP NOT NULL DEFAULT NOW(),
  "saida" TIMESTAMP,
  "observacoes" TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "chamados_sac" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "protocolo" VARCHAR(20) NOT NULL,
  "clienteId" INTEGER,
  "clienteNome" VARCHAR(255),
  "canal" VARCHAR(50) DEFAULT 'telefone',
  "assunto" VARCHAR(255) NOT NULL,
  "descricao" TEXT NOT NULL,
  "status" "status_sac" NOT NULL DEFAULT 'aberto',
  "prioridade" "prioridade_sac" NOT NULL DEFAULT 'media',
  "responsavelId" INTEGER,
  "resolucao" TEXT,
  "resolvidoEm" TIMESTAMP,
  "nps" INTEGER,
  "createdBy" INTEGER,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "interacoes_sac" (
  "id" SERIAL PRIMARY KEY,
  "chamadoId" INTEGER NOT NULL,
  "userId" INTEGER NOT NULL,
  "mensagem" TEXT NOT NULL,
  "interno" BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "banco_horas" (
  "id" SERIAL PRIMARY KEY,
  "empresaId" INTEGER NOT NULL,
  "funcionarioId" INTEGER NOT NULL,
  "data" DATE NOT NULL,
  "horasTrabalhadas" VARCHAR(10),
  "horasExtras" VARCHAR(10),
  "horasDevidas" VARCHAR(10),
  "saldo" VARCHAR(10),
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "fotos_conferencia" (
  "id" SERIAL PRIMARY KEY,
  "conferenciaId" INTEGER NOT NULL,
  "empresaId" INTEGER NOT NULL,
  "tipo" VARCHAR(50) NOT NULL,
  "descricao" VARCHAR(255),
  "url" TEXT NOT NULL,
  "momento" VARCHAR(20) NOT NULL,
  "uploadedBy" INTEGER,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE TABLE IF NOT EXISTS "itens_conferencia" (
  "id" SERIAL PRIMARY KEY,
  "conferenciaId" INTEGER NOT NULL,
  "item" VARCHAR(255) NOT NULL,
  "conforme" BOOLEAN,
  "observacao" TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
)`,
  `CREATE INDEX IF NOT EXISTS idx_leads_empresa ON "leads"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_leads_status ON "leads"("status")`,
  `CREATE INDEX IF NOT EXISTS idx_negociacoes_empresa ON "negociacoes"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_negociacoes_funil ON "negociacoes"("funilId")`,
  `CREATE INDEX IF NOT EXISTS idx_pedidos_empresa ON "pedidos"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_estoque_empresa ON "estoque"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_estoque_produto ON "estoque"("produtoId")`,
  // Tabela principal de chamados TI
  `CREATE TABLE IF NOT EXISTS "tickets_ti" (
    "id" serial PRIMARY KEY NOT NULL,
    "empresaId" integer NOT NULL,
    "protocolo" varchar(20) NOT NULL,
    "solicitanteId" integer NOT NULL,
    "titulo" varchar(255) NOT NULL,
    "descricao" text NOT NULL,
    "categoria" "categoria_ticket_ti" NOT NULL DEFAULT 'outro',
    "prioridade" "prioridade_ticket_ti" NOT NULL DEFAULT 'media',
    "status" "status_ticket_ti" NOT NULL DEFAULT 'aberto',
    "responsavelId" integer,
    "tecnicoId" integer,
    "resolucao" text,
    "resolvidoEm" timestamp,
    "slaHoras" integer DEFAULT 24,
    "prazoAtendimento" timestamp,
    "tempoResolucaoMin" integer,
    "ativoId" integer,
    "setor" varchar(100),
    "impacto" varchar(50) DEFAULT 'medio',
    "numeroOS" varchar(30),
    "createdAt" timestamp NOT NULL DEFAULT NOW(),
    "updatedAt" timestamp NOT NULL DEFAULT NOW(),
    "deletedAt" timestamp
  )`,
  `CREATE INDEX IF NOT EXISTS idx_tickets_ti_empresa ON "tickets_ti"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_tickets_ti_status ON "tickets_ti"("status")`,
  `CREATE INDEX IF NOT EXISTS idx_ativos_ti_empresa ON "ativos_ti"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_ia_sessoes_empresa ON "ia_sessoes"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_ia_mensagens_sessao ON "ia_mensagens"("sessaoId")`,
  `CREATE INDEX IF NOT EXISTS idx_auditoria_empresa ON "auditoria_detalhada"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_auditoria_user ON "auditoria_detalhada"("userId")`,
  `CREATE INDEX IF NOT EXISTS idx_registros_ponto_empresa ON "registros_ponto"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_registros_ponto_funcionario ON "registros_ponto"("funcionarioId")`,
  `CREATE INDEX IF NOT EXISTS idx_integracoes_empresa ON "integracoes"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_chamados_sac_empresa ON "chamados_sac"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_visitantes_empresa ON "visitantes"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_conferencia_empresa ON "conferencia_veiculos"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_bi_dashboards_empresa ON "bi_dashboards"("empresaId")`,

  // ─── TI EXPANDIDO ─────────────────────────────────────────────────────────
  `CREATE TABLE IF NOT EXISTS "ticket_mensagens" (
    "id" serial PRIMARY KEY NOT NULL,
    "ticketId" integer NOT NULL,
    "empresaId" integer NOT NULL,
    "autorId" integer NOT NULL,
    "conteudo" text,
    "tipo" varchar(20) DEFAULT 'texto' NOT NULL,
    "fileUrl" text,
    "fileName" varchar(255),
    "fileType" varchar(100),
    "interno" boolean DEFAULT false NOT NULL,
    "createdAt" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_ticket_mensagens_ticket ON "ticket_mensagens"("ticketId")`,
  `CREATE INDEX IF NOT EXISTS idx_ticket_mensagens_empresa ON "ticket_mensagens"("empresaId")`,

  `CREATE TABLE IF NOT EXISTS "licencas_ti" (
    "id" serial PRIMARY KEY NOT NULL,
    "empresaId" integer NOT NULL,
    "software" varchar(200) NOT NULL,
    "fabricante" varchar(200),
    "tipo" varchar(50) DEFAULT 'assinatura' NOT NULL,
    "totalLicencas" integer DEFAULT 1 NOT NULL,
    "licencasUsadas" integer DEFAULT 0 NOT NULL,
    "chave" text,
    "dataCompra" date,
    "dataExpiracao" date,
    "custoMensal" numeric(10,2) DEFAULT 0,
    "custoAnual" numeric(10,2) DEFAULT 0,
    "fornecedor" varchar(200),
    "observacoes" text,
    "ativo" boolean DEFAULT true NOT NULL,
    "createdAt" timestamp DEFAULT now() NOT NULL,
    "updatedAt" timestamp DEFAULT now() NOT NULL,
    "deletedAt" timestamp
  )`,
  `CREATE INDEX IF NOT EXISTS idx_licencas_ti_empresa ON "licencas_ti"("empresaId")`,

  `CREATE TABLE IF NOT EXISTS "servidores_ti" (
    "id" serial PRIMARY KEY NOT NULL,
    "empresaId" integer NOT NULL,
    "nome" varchar(200) NOT NULL,
    "tipo" varchar(50) DEFAULT 'fisico' NOT NULL,
    "ip" varchar(50),
    "so" varchar(100),
    "cpu" varchar(100),
    "ramGb" integer,
    "discoGb" integer,
    "localizacao" varchar(200),
    "funcao" varchar(200),
    "status" varchar(50) DEFAULT 'online' NOT NULL,
    "cpuUso" integer DEFAULT 0,
    "ramUso" integer DEFAULT 0,
    "discoUso" integer DEFAULT 0,
    "temperatura" integer DEFAULT 0,
    "ultimoPing" timestamp,
    "observacoes" text,
    "ativo" boolean DEFAULT true NOT NULL,
    "createdAt" timestamp DEFAULT now() NOT NULL,
    "updatedAt" timestamp DEFAULT now() NOT NULL,
    "deletedAt" timestamp
  )`,
  `CREATE INDEX IF NOT EXISTS idx_servidores_ti_empresa ON "servidores_ti"("empresaId")`,

  `CREATE TABLE IF NOT EXISTS "acessos_remotos_ti" (
    "id" serial PRIMARY KEY NOT NULL,
    "empresaId" integer NOT NULL,
    "maquina" varchar(200) NOT NULL,
    "setor" varchar(100),
    "responsavelId" integer,
    "anydesk" varchar(50),
    "teamviewer" varchar(50),
    "rdp" varchar(100),
    "vpn" varchar(100),
    "ultimaSessao" timestamp,
    "observacoes" text,
    "ativo" boolean DEFAULT true NOT NULL,
    "createdAt" timestamp DEFAULT now() NOT NULL,
    "updatedAt" timestamp DEFAULT now() NOT NULL,
    "deletedAt" timestamp
  )`,
  `CREATE INDEX IF NOT EXISTS idx_acessos_remotos_empresa ON "acessos_remotos_ti"("empresaId")`,

  `CREATE TABLE IF NOT EXISTS "compras_ti" (
    "id" serial PRIMARY KEY NOT NULL,
    "empresaId" integer NOT NULL,
    "solicitanteId" integer NOT NULL,
    "titulo" varchar(255) NOT NULL,
    "descricao" text,
    "categoria" varchar(100) DEFAULT 'hardware',
    "quantidade" integer DEFAULT 1 NOT NULL,
    "valorUnitario" numeric(10,2),
    "valorTotal" numeric(10,2),
    "fornecedor" varchar(200),
    "status" varchar(50) DEFAULT 'solicitado' NOT NULL,
    "prioridade" varchar(20) DEFAULT 'media' NOT NULL,
    "aprovadoPor" integer,
    "aprovadoEm" timestamp,
    "observacoes" text,
    "createdAt" timestamp DEFAULT now() NOT NULL,
    "updatedAt" timestamp DEFAULT now() NOT NULL,
    "deletedAt" timestamp
  )`,
  `CREATE INDEX IF NOT EXISTS idx_compras_ti_empresa ON "compras_ti"("empresaId")`,

  `CREATE TABLE IF NOT EXISTS "cmdb_ti" (
    "id" serial PRIMARY KEY NOT NULL,
    "empresaId" integer NOT NULL,
    "nome" varchar(200) NOT NULL,
    "tipo" varchar(100) NOT NULL,
    "categoria" varchar(100),
    "fabricante" varchar(200),
    "modelo" varchar(200),
    "versao" varchar(100),
    "ip" varchar(50),
    "mac" varchar(50),
    "localizacao" varchar(200),
    "responsavelId" integer,
    "dependencias" text,
    "status" varchar(50) DEFAULT 'ativo' NOT NULL,
    "criticidade" varchar(20) DEFAULT 'media' NOT NULL,
    "observacoes" text,
    "ativo" boolean DEFAULT true NOT NULL,
    "createdAt" timestamp DEFAULT now() NOT NULL,
    "updatedAt" timestamp DEFAULT now() NOT NULL,
    "deletedAt" timestamp
  )`,
  `CREATE INDEX IF NOT EXISTS idx_cmdb_ti_empresa ON "cmdb_ti"("empresaId")`,

  `CREATE TABLE IF NOT EXISTS "manutencoes_ti" (
    "id" serial PRIMARY KEY NOT NULL,
    "empresaId" integer NOT NULL,
    "ativoId" integer,
    "servidorId" integer,
    "tipo" varchar(50) DEFAULT 'corretiva' NOT NULL,
    "titulo" varchar(255) NOT NULL,
    "descricao" text,
    "tecnicoId" integer,
    "status" varchar(50) DEFAULT 'agendada' NOT NULL,
    "prioridade" varchar(20) DEFAULT 'media' NOT NULL,
    "agendadoPara" timestamp,
    "iniciadoEm" timestamp,
    "concluidoEm" timestamp,
    "pecasUtilizadas" text,
    "custo" numeric(10,2) DEFAULT 0,
    "resolucao" text,
    "ticketId" integer,
    "createdAt" timestamp DEFAULT now() NOT NULL,
    "updatedAt" timestamp DEFAULT now() NOT NULL,
    "deletedAt" timestamp
  )`,
  `CREATE INDEX IF NOT EXISTS idx_manutencoes_ti_empresa ON "manutencoes_ti"("empresaId")`,

  // Colunas extras em ativos_ti
  `ALTER TABLE "ativos_ti" ADD COLUMN IF NOT EXISTS "hostname" varchar(100)`,
  `ALTER TABLE "ativos_ti" ADD COLUMN IF NOT EXISTS "so" varchar(100)`,
  `ALTER TABLE "ativos_ti" ADD COLUMN IF NOT EXISTS "anydesk" varchar(50)`,
  `ALTER TABLE "ativos_ti" ADD COLUMN IF NOT EXISTS "teamviewer" varchar(50)`,
  `ALTER TABLE "ativos_ti" ADD COLUMN IF NOT EXISTS "ip" varchar(50)`,
  `ALTER TABLE "ativos_ti" ADD COLUMN IF NOT EXISTS "cpuUso" integer DEFAULT 0`,
  `ALTER TABLE "ativos_ti" ADD COLUMN IF NOT EXISTS "ramUso" integer DEFAULT 0`,
  `ALTER TABLE "ativos_ti" ADD COLUMN IF NOT EXISTS "discoSaude" integer DEFAULT 100`,
  `ALTER TABLE "ativos_ti" ADD COLUMN IF NOT EXISTS "temperatura" integer DEFAULT 0`,
  `ALTER TABLE "ativos_ti" ADD COLUMN IF NOT EXISTS "ultimoPing" timestamp`,
  `ALTER TABLE "ativos_ti" ADD COLUMN IF NOT EXISTS "dataAquisicao" date`,
  `ALTER TABLE "ativos_ti" ADD COLUMN IF NOT EXISTS "valorAquisicao" numeric(10,2)`,

  // Colunas extras em tickets_ti
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "anexoUrl" text`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "anexoNome" varchar(255)`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "ativoId" integer`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "tempoResolucaoMin" integer`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "numeroOS" varchar(30)`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "prazoAtendimento" timestamp`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "slaHoras" integer DEFAULT 24`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "tecnicoId" integer`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "setor" varchar(100)`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "impacto" varchar(50) DEFAULT 'medio'`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "resolvidoEm" timestamp`,

  // ─── BLOCO DE NOTAS ────────────────────────────────────────────────────────
  `CREATE TABLE IF NOT EXISTS "notas" (
    "id" serial PRIMARY KEY NOT NULL,
    "empresaId" integer NOT NULL,
    "userId" integer NOT NULL,
    "titulo" varchar(500) NOT NULL DEFAULT 'Sem título',
    "conteudo" text DEFAULT '' NOT NULL,
    "pasta" varchar(100) DEFAULT 'Geral',
    "tags" text DEFAULT '',
    "cor" varchar(20) DEFAULT 'default',
    "fixada" boolean DEFAULT false NOT NULL,
    "arquivada" boolean DEFAULT false NOT NULL,
    "compartilhada" boolean DEFAULT false NOT NULL,
    "createdAt" timestamp DEFAULT now() NOT NULL,
    "updatedAt" timestamp DEFAULT now() NOT NULL,
    "deletedAt" timestamp
  )`,
  `CREATE INDEX IF NOT EXISTS idx_notas_user ON "notas"("userId")`,
  `CREATE INDEX IF NOT EXISTS idx_notas_empresa ON "notas"("empresaId")`,

  // ─── MONITORAMENTO REAL DE PCs ──────────────────────────────────────────────
  `CREATE TABLE IF NOT EXISTS "monitor_agentes" (
    "id" serial PRIMARY KEY NOT NULL,
    "empresaId" integer NOT NULL,
    "ativoId" integer,
    "hostname" varchar(200) NOT NULL,
    "ip" varchar(50),
    "mac" varchar(50),
    "so" varchar(100),
    "versaoAgente" varchar(20),
    "token" varchar(100) NOT NULL,
    "ultimoContato" timestamp,
    "online" boolean DEFAULT false NOT NULL,
    "ativo" boolean DEFAULT true NOT NULL,
    "createdAt" timestamp DEFAULT now() NOT NULL,
    "updatedAt" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_monitor_agentes_token ON "monitor_agentes"("token")`,
  `CREATE INDEX IF NOT EXISTS idx_monitor_agentes_empresa ON "monitor_agentes"("empresaId")`,

  `CREATE TABLE IF NOT EXISTS "monitor_metricas" (
    "id" bigserial PRIMARY KEY NOT NULL,
    "agenteId" integer NOT NULL,
    "empresaId" integer NOT NULL,
    "coletadoEm" timestamp NOT NULL DEFAULT now(),
    "cpuUso" numeric(5,2),
    "cpuTemp" numeric(5,1),
    "cpuFreqMhz" integer,
    "ramTotalMb" integer,
    "ramUsadaMb" integer,
    "ramUsoPct" numeric(5,2),
    "discoTotalGb" numeric(8,2),
    "discoUsadoGb" numeric(8,2),
    "discoUsoPct" numeric(5,2),
    "redeEnviadoKb" numeric(12,2),
    "redeRecebidoKb" numeric(12,2),
    "latenciaMs" integer,
    "processos" integer,
    "usuarioLogado" varchar(100),
    "uptime" integer
  )`,
  `CREATE INDEX IF NOT EXISTS idx_monitor_metricas_agente ON "monitor_metricas"("agenteId")`,
  `CREATE INDEX IF NOT EXISTS idx_monitor_metricas_empresa ON "monitor_metricas"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_monitor_metricas_coletado ON "monitor_metricas"("coletadoEm" DESC)`,

  `CREATE TABLE IF NOT EXISTS "monitor_eventos" (
    "id" bigserial PRIMARY KEY NOT NULL,
    "agenteId" integer NOT NULL,
    "empresaId" integer NOT NULL,
    "tipo" varchar(50) NOT NULL,
    "descricao" text,
    "severidade" varchar(20) DEFAULT 'info' NOT NULL,
    "valor" numeric(10,2),
    "ocorridoEm" timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_monitor_eventos_agente ON "monitor_eventos"("agenteId")`,
  `CREATE INDEX IF NOT EXISTS idx_monitor_eventos_empresa ON "monitor_eventos"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_monitor_eventos_ocorrido ON "monitor_eventos"("ocorridoEm" DESC)`,

  // ── Tabela de códigos de pareamento PC↔Synapse ──────────────────────────
  `CREATE TABLE IF NOT EXISTS "agent_pairing_codes" (
    "id" serial PRIMARY KEY NOT NULL,
    "empresaId" integer NOT NULL,
    "codigo" varchar(20) NOT NULL UNIQUE,
    "descricao" varchar(255),
    "ativoId" integer,
    "usado" boolean DEFAULT false NOT NULL,
    "agenteId" integer,
    "criadoPor" integer NOT NULL,
    "expiresAt" timestamp NOT NULL,
    "usadoEm" timestamp,
    "createdAt" timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_pairing_empresa ON "agent_pairing_codes"("empresaId")`,
  `CREATE INDEX IF NOT EXISTS idx_pairing_codigo ON "agent_pairing_codes"("codigo")`,

  // Colunas extras para monitor_agentes
  `ALTER TABLE monitor_agentes ADD COLUMN IF NOT EXISTS "anydeskId" varchar(50)`,
  `ALTER TABLE monitor_agentes ADD COLUMN IF NOT EXISTS "status" varchar(20) DEFAULT 'offline'`,
  `ALTER TABLE monitor_agentes ADD COLUMN IF NOT EXISTS "deletedAt" timestamp`,
  `ALTER TABLE monitor_agentes ADD COLUMN IF NOT EXISTS "pairingCode" varchar(20)`,
  `ALTER TABLE monitor_agentes ADD COLUMN IF NOT EXISTS "fingerprint" varchar(200)`,
  `ALTER TABLE monitor_agentes ADD COLUMN IF NOT EXISTS "ultimaVersao" varchar(20)`,
  `ALTER TABLE monitor_agentes ADD COLUMN IF NOT EXISTS "setor" varchar(100)`,

  // Colunas extras para monitor_metricas
  `ALTER TABLE monitor_metricas ADD COLUMN IF NOT EXISTS "anydeskId" varchar(50)`,
  `ALTER TABLE monitor_metricas ADD COLUMN IF NOT EXISTS "topProcessos" jsonb`,

  // Adicionar agentToken à tabela de empresas para identificação do tenant
  `ALTER TABLE empresas ADD COLUMN IF NOT EXISTS "agentToken" varchar(64) UNIQUE`,
  `ALTER TABLE empresas ADD COLUMN IF NOT EXISTS "codigoConvite" varchar(50) UNIQUE`,

  // Particionamento por tempo: view agregada por hora
  `CREATE OR REPLACE VIEW monitor_metricas_hora AS
    SELECT
      "agenteId", "empresaId",
      date_trunc('hour', "coletadoEm") as hora,
      round(avg("cpuUso")::numeric, 1) as cpu_medio,
      round(max("cpuUso")::numeric, 1) as cpu_pico,
      round(avg("ramUsoPct")::numeric, 1) as ram_medio,
      round(max("ramUsoPct")::numeric, 1) as ram_pico,
      round(avg("discoUsoPct")::numeric, 1) as disco_medio,
      round(avg("latenciaMs")::numeric, 0) as latencia_media,
      count(*) as amostras
    FROM monitor_metricas
    GROUP BY "agenteId", "empresaId", date_trunc('hour', "coletadoEm")`,
  // Fix veiculos table - make optional columns nullable in case old DB had them as NOT NULL
  `ALTER TABLE "veiculos" ALTER COLUMN "cavaloPrincipalId" DROP NOT NULL`,
  `ALTER TABLE "veiculos" ALTER COLUMN "motoristaId" DROP NOT NULL`,
  `ALTER TABLE "veiculos" ALTER COLUMN "ajudanteId" DROP NOT NULL`,
  `ALTER TABLE "veiculos" ALTER COLUMN "renavam" DROP NOT NULL`,
  `ALTER TABLE "veiculos" ALTER COLUMN "chassi" DROP NOT NULL`,
  `ALTER TABLE "veiculos" ALTER COLUMN "marca" DROP NOT NULL`,
  `ALTER TABLE "veiculos" ALTER COLUMN "modelo" DROP NOT NULL`,
  `ALTER TABLE "veiculos" ALTER COLUMN "ano" DROP NOT NULL`,
  `ALTER TABLE "veiculos" ALTER COLUMN "cor" DROP NOT NULL`,
  `ALTER TABLE "veiculos" ALTER COLUMN "capacidadeCarga" DROP NOT NULL`,
  `ALTER TABLE "veiculos" ALTER COLUMN "kmAtual" DROP NOT NULL`,
  `ALTER TABLE "veiculos" ALTER COLUMN "mediaConsumo" DROP NOT NULL`,
  `ALTER TABLE "veiculos" ALTER COLUMN "vencimentoCrlv" DROP NOT NULL`,
  `ALTER TABLE "veiculos" ALTER COLUMN "vencimentoSeguro" DROP NOT NULL`,
  `ALTER TABLE "veiculos" ADD COLUMN IF NOT EXISTS "classificacao" integer DEFAULT 0`,
  `ALTER TABLE "veiculos" ADD COLUMN IF NOT EXISTS "deleteReason" text`,
  `ALTER TABLE "veiculos" ADD COLUMN IF NOT EXISTS "deletedBy" integer`,
  // --- TAREFAS / PROJETOS ---
  `CREATE TABLE IF NOT EXISTS "projetos" (
    "id" serial PRIMARY KEY,
    "empresaId" integer NOT NULL,
    "nome" varchar(200) NOT NULL,
    "descricao" text,
    "cor" varchar(20) DEFAULT '#6366f1',
    "ativo" boolean DEFAULT true,
    "createdAt" timestamp DEFAULT now(),
    "updatedAt" timestamp DEFAULT now()
  )`,

  `CREATE TABLE IF NOT EXISTS "tarefas" (
    "id" serial PRIMARY KEY,
    "empresaId" integer NOT NULL,
    "projetoId" integer,
    "titulo" varchar(500) NOT NULL,
    "descricao" text,
    "status" varchar(30) DEFAULT 'backlog',
    "prioridade" varchar(20) DEFAULT 'media',
    "responsavelId" integer,
    "responsavelNome" varchar(200),
    "prazo" timestamp,
    "estimativaHoras" numeric(8,2),
    "progresso" integer DEFAULT 0,
    "sprint" varchar(100),
    "tags" text DEFAULT '[]',
    "criadoPorId" integer,
    "createdAt" timestamp DEFAULT now(),
    "updatedAt" timestamp DEFAULT now()
  )`,

  `CREATE TABLE IF NOT EXISTS "tarefa_comentarios" (
    "id" serial PRIMARY KEY,
    "tarefaId" integer NOT NULL,
    "userId" integer NOT NULL,
    "userName" varchar(200),
    "conteudo" text NOT NULL,
    "createdAt" timestamp DEFAULT now()
  )`,
  // --- CHAT: colunas de arquivo ---
  `ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "fileUrl" text`,
  `ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "fileName" varchar(255)`,
  `ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "fileSize" integer`,
  `ALTER TABLE "chat_messages" ADD COLUMN IF NOT EXISTS "mimeType" varchar(100)`,

  // --- USERS: campos de perfil ---
  `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "avatarUrl" text`,
  `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "bio" text`,
  `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "cargo" varchar(100)`,
  `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "departamento" varchar(100)`,
  `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "idioma" varchar(10) DEFAULT 'pt'`,
  `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "tema" varchar(20) DEFAULT 'dark'`,

  // ── Agentes de Monitoramento ─────────────────────────────────────────────────
  `CREATE TABLE IF NOT EXISTS "agent_pair_codes" (
    "id" serial PRIMARY KEY,
    "empresaId" integer NOT NULL,
    "code" varchar(30) NOT NULL UNIQUE,
    "label" varchar(100),
    "used" boolean DEFAULT false,
    "usedAt" timestamptz,
    "createdBy" integer,
    "createdAt" timestamptz DEFAULT now(),
    "expiresAt" timestamptz
  )`,
  `CREATE TABLE IF NOT EXISTS "agent_devices" (
    "id" serial PRIMARY KEY,
    "empresaId" integer NOT NULL,
    "deviceId" varchar(50) NOT NULL UNIQUE,
    "hostname" varchar(200),
    "token" varchar(200) NOT NULL,
    "platform" jsonb,
    "agentVersion" varchar(20),
    "status" varchar(20) DEFAULT 'online',
    "lastSeenAt" timestamptz DEFAULT now(),
    "pairedAt" timestamptz DEFAULT now(),
    "label" varchar(100),
    "createdAt" timestamptz DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS "agent_metrics" (
    "id" serial PRIMARY KEY,
    "deviceId" varchar(50) NOT NULL,
    "empresaId" integer,
    "timestamp" timestamptz NOT NULL,
    "cpu" jsonb,
    "ram" jsonb,
    "disks" jsonb,
    "network" jsonb,
    "temperatures" jsonb,
    "topProcesses" jsonb,
    "uptimeHours" real,
    "bootTime" timestamptz,
    "createdAt" timestamptz DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS "agent_metrics_deviceId_idx" ON "agent_metrics" ("deviceId")`,
  `CREATE INDEX IF NOT EXISTS "agent_metrics_timestamp_idx" ON "agent_metrics" ("timestamp" DESC)`,

  // ── Acessos Remotos TI ───────────────────────────────────────────────────────
  `CREATE TABLE IF NOT EXISTS "acessos_ti" (
    "id" serial PRIMARY KEY,
    "empresaId" integer NOT NULL,
    "usuarioId" integer,
    "nome" varchar(200) NOT NULL,
    "tipo" varchar(30) DEFAULT 'outro',
    "host" varchar(255),
    "porta" integer,
    "usuario" varchar(100),
    "anydesk_id" varchar(50),
    "setor" varchar(100),
    "observacoes" text,
    "ativo" boolean DEFAULT true,
    "createdAt" timestamptz DEFAULT now(),
    "updatedAt" timestamptz DEFAULT now(),
    "deletedAt" timestamptz
  )`,
  `CREATE INDEX IF NOT EXISTS idx_acessos_ti_empresa ON "acessos_ti"("empresaId")`,
  // Colunas extras em agent_pairing_codes
  `ALTER TABLE agent_pairing_codes ADD COLUMN IF NOT EXISTS "hostnameVinculado" varchar(200)`,
  `ALTER TABLE monitor_agentes ADD COLUMN IF NOT EXISTS "user_id" varchar(255)`,
  `ALTER TABLE monitor_agentes ADD COLUMN IF NOT EXISTS "department_id" varchar(255)`,
  `ALTER TABLE agent_pairing_codes ADD COLUMN IF NOT EXISTS "user_id" varchar(255)`,
  `ALTER TABLE agent_pairing_codes ADD COLUMN IF NOT EXISTS "department_id" varchar(255)`,
  `ALTER TABLE agent_pairing_codes ADD COLUMN IF NOT EXISTS "is_used" boolean DEFAULT false`,
]; // --- TICKETS_TI: Correção de colunas faltantes ---
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "status" varchar(30) NOT NULL DEFAULT 'aberto'`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "prioridade" varchar(20) NOT NULL DEFAULT 'media'`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "categoria" varchar(50) NOT NULL DEFAULT 'outro'`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "tecnicoId" integer`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "responsavelId" integer`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "resolucao" text`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "resolvidoEm" timestamp`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "slaHoras" integer DEFAULT 24`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "prazoAtendimento" timestamp`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "tempoResolucaoMin" integer`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "ativoId" integer`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "setor" varchar(100)`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "impacto" varchar(50) DEFAULT 'medio'`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "numeroOS" varchar(30)`,
  `ALTER TABLE "tickets_ti" ADD COLUMN IF NOT EXISTS "deletedAt" timestamp`,

  // ── Certificados Digitais TI ─────────────────────────────────────────────────
  `CREATE TABLE IF NOT EXISTS "certificados_ti" (
    "id" serial PRIMARY KEY,
    "empresaId" integer NOT NULL,
    "nome" varchar(255) NOT NULL,
    "tipo" varchar(50) NOT NULL,
    "vencimento" timestamp NOT NULL,
    "senha" text,
    "observacoes" text,
    "alertaEnviado" boolean DEFAULT false,
    "createdAt" timestamp DEFAULT now() NOT NULL,
    "updatedAt" timestamp DEFAULT now() NOT NULL,
    "deletedAt" timestamp
  )`,
  `CREATE INDEX IF NOT EXISTS "certificados_ti_empresa_id_idx" ON "certificados_ti" ("empresaId")`,
];

export async function runInlineMigrations(): Promise<void> {
  const client = await getRawClient();
  if (!client) {
    console.warn("[Migration] Cliente postgres não encontrado para migrações inline");
    return;
  }
  let applied = 0;
  let errors = 0;
  for (const sql of MIGRATION_STATEMENTS) {
    try {
      await client.unsafe(sql);
      applied++;
    } catch (err: any) {
      // Ignore "already exists" errors - these are expected on re-runs
      const msg = err?.message || "";
      if (!msg.includes("already exists") && !msg.includes("duplicate") && !msg.includes("42P07") && !msg.includes("42710")) {
        console.warn(`[Migration] Aviso em statement: ${msg.substring(0, 100)}`);
        errors++;
      }
    }
  }
  console.log(`[Migration] Inline: ${applied} statements aplicados, ${errors} erros ignorados`);
}
