CREATE TABLE "abastecimentos" (
	"id" serial NOT NULL,
	"empresaId" integer NOT NULL,
	"veiculoId" integer NOT NULL,
	"motoristaId" integer,
	"data" date NOT NULL,
	"tipoCombustivel" text NOT NULL,
	"quantidade" decimal(8,3) NOT NULL,
	"valorUnitario" decimal(8,3),
	"valorTotal" decimal(10,2),
	"kmAtual" integer,
	"kmRodado" integer,
	"mediaConsumo" decimal(5,2),
	"local" varchar(255),
	"tipoAbastecimento" text DEFAULT 'interno',
	"notaFiscal" varchar(50),
	"observacoes" text,
	"createdAt" timestamptz NOT NULL DEFAULT NOW(),
	"updatedAt" timestamptz NOT NULL DEFAULT NOW(),
	"deletedAt" timestamptz,
	"deletedBy" integer,
	"deleteReason" text,
	CONSTRAINT "abastecimentos_id" PRIMARY KEY ("id")
);
CREATE TABLE "acidentes" (
	"id" serial NOT NULL,
	"empresaId" integer NOT NULL,
	"veiculoId" integer NOT NULL,
	"motoristaId" integer,
	"data" date NOT NULL,
	"local" varchar(255),
	"descricao" text NOT NULL,
	"boletimOcorrencia" varchar(50),
	"valorDano" decimal(10,2),
	"status" text NOT NULL DEFAULT 'aberto',
	"observacoes" text,
	"createdAt" timestamptz NOT NULL DEFAULT NOW(),
	"updatedAt" timestamptz NOT NULL DEFAULT NOW(),
	"deletedAt" timestamptz,
	"deletedBy" integer,
	"deleteReason" text,
	CONSTRAINT "acidentes_id" PRIMARY KEY ("id")
);
CREATE TABLE "adiantamentos" (
	"id" serial NOT NULL,
	"empresaId" integer NOT NULL,
	"funcionarioId" integer NOT NULL,
	"viagemId" integer,
	"valor" decimal(10,2) NOT NULL,
	"formaPagamento" text NOT NULL,
	"data" date NOT NULL,
	"status" text NOT NULL DEFAULT 'pendente',
	"valorAcertado" decimal(10,2),
	"dataAcerto" date,
	"saldo" decimal(10,2),
	"observacoes" text,
	"createdAt" timestamptz NOT NULL DEFAULT NOW(),
	"updatedAt" timestamptz NOT NULL DEFAULT NOW(),
	"deletedAt" timestamptz,
	"deletedBy" integer,
	"deleteReason" text,
	CONSTRAINT "adiantamentos_id" PRIMARY KEY ("id")
);
CREATE TABLE "audit_log" (
	"id" bigint AUTO_INCREMENT NOT NULL,
	"empresaId" integer,
	"userId" integer NOT NULL,
	"userName" varchar(255),
	"acao" varchar(50) NOT NULL,
	"tabela" varchar(100) NOT NULL,
	"registroId" integer NOT NULL,
	"dadosAntes" text,
	"dadosDepois" text,
	"ip" varchar(45),
	"userAgent" text,
	"createdAt" timestamptz NOT NULL DEFAULT NOW(),
	CONSTRAINT "audit_log_id" PRIMARY KEY ("id")
);
CREATE TABLE "checklists" (
	"id" serial NOT NULL,
	"empresaId" integer NOT NULL,
	"veiculoId" integer NOT NULL,
	"cavaloPrincipalId" integer,
	"motoristaId" integer,
	"turno" text,
	"tipo" text NOT NULL DEFAULT 'retorno',
	"cracha" text,
	"cnh" text,
	"documentosVeiculo" text,
	"epi" text,
	"computadorBordo" text,
	"cinto" text,
	"banco" text,
	"direcao" text,
	"luzesPainel" text,
	"tacografo" text,
	"extintor" text,
	"portas" text,
	"limpador" text,
	"buzina" text,
	"freioDeMao" text,
	"alarmeCacamba" text,
	"cabineLimpa" text,
	"objetosSoltos" text,
	"pneus" text,
	"vazamentos" text,
	"trianguloCones" text,
	"espelhos" text,
	"lonaCarga" text,
	"faixasRefletivas" text,
	"luzesLaterais" text,
	"luzesFreio" text,
	"farol" text,
	"piscaAlerta" text,
	"re" text,
	"setas" text,
	"macacoEstepe" text,
	"lanternas" text,
	"itensNaoConformes" integer DEFAULT 0,
	"observacoes" text,
	"assinaturaMotorista" text,
	"createdAt" timestamptz NOT NULL DEFAULT NOW(),
	"updatedAt" timestamptz NOT NULL DEFAULT NOW(),
	"deletedAt" timestamptz,
	"deletedBy" integer,
	"deleteReason" text,
	CONSTRAINT "checklists_id" PRIMARY KEY ("id")
);
CREATE TABLE "contas_pagar" (
	"id" serial NOT NULL,
	"empresaId" integer NOT NULL,
	"descricao" text NOT NULL,
	"categoria" text NOT NULL,
	"valor" decimal(10,2) NOT NULL,
	"dataVencimento" date NOT NULL,
	"dataPagamento" date,
	"status" text NOT NULL DEFAULT 'pendente',
	"fornecedor" varchar(255),
	"notaFiscal" varchar(50),
	"veiculoId" integer,
	"funcionarioId" integer,
	"viagemId" integer,
	"comprovante" text,
	"observacoes" text,
	"createdAt" timestamptz NOT NULL DEFAULT NOW(),
	"updatedAt" timestamptz NOT NULL DEFAULT NOW(),
	"deletedAt" timestamptz,
	"deletedBy" integer,
	"deleteReason" text,
	CONSTRAINT "contas_pagar_id" PRIMARY KEY ("id")
);
CREATE TABLE "contas_receber" (
	"id" serial NOT NULL,
	"empresaId" integer NOT NULL,
	"descricao" text NOT NULL,
	"categoria" text NOT NULL,
	"valor" decimal(10,2) NOT NULL,
	"dataVencimento" date NOT NULL,
	"dataRecebimento" date,
	"status" text NOT NULL DEFAULT 'pendente',
	"cliente" varchar(255),
	"notaFiscal" varchar(50),
	"cteNumero" varchar(50),
	"viagemId" integer,
	"observacoes" text,
	"createdAt" timestamptz NOT NULL DEFAULT NOW(),
	"updatedAt" timestamptz NOT NULL DEFAULT NOW(),
	"deletedAt" timestamptz,
	"deletedBy" integer,
	"deleteReason" text,
	CONSTRAINT "contas_receber_id" PRIMARY KEY ("id")
);
CREATE TABLE "controle_tanque" (
	"id" serial NOT NULL,
	"empresaId" integer NOT NULL,
	"tipo" text NOT NULL,
	"data" date NOT NULL,
	"operacao" text NOT NULL,
	"quantidade" decimal(8,3) NOT NULL,
	"valorUnitario" decimal(8,3),
	"valorTotal" decimal(10,2),
	"fornecedor" varchar(255),
	"notaFiscal" varchar(50),
	"veiculoId" integer,
	"motoristaId" integer,
	"saldoAnterior" decimal(8,3),
	"saldoAtual" decimal(8,3),
	"observacoes" text,
	"createdAt" timestamptz NOT NULL DEFAULT NOW(),
	"deletedAt" timestamptz,
	"deletedBy" integer,
	"deleteReason" text,
	CONSTRAINT "controle_tanque_id" PRIMARY KEY ("id")
);
CREATE TABLE "despesas_viagem" (
	"id" serial NOT NULL,
	"viagemId" integer NOT NULL,
	"empresaId" integer NOT NULL,
	"tipo" text NOT NULL,
	"descricao" text,
	"valor" decimal(10,2) NOT NULL,
	"data" date,
	"comprovante" text,
	"createdAt" timestamptz NOT NULL DEFAULT NOW(),
	"deletedAt" timestamptz,
	"deletedBy" integer,
	"deleteReason" text,
	CONSTRAINT "despesas_viagem_id" PRIMARY KEY ("id")
);
CREATE TABLE "empresas" (
	"id" serial NOT NULL,
	"nome" varchar(255) NOT NULL,
	"cnpj" varchar(18),
	"telefone" varchar(20),
	"email" varchar(320),
	"endereco" text,
	"cidade" varchar(100),
	"estado" varchar(2),
	"ativo" boolean NOT NULL DEFAULT TRUE,
	"createdAt" timestamptz NOT NULL DEFAULT NOW(),
	"updatedAt" timestamptz NOT NULL DEFAULT NOW(),
	"deletedAt" timestamptz,
	"deletedBy" integer,
	"deleteReason" text,
	CONSTRAINT "empresas_id" PRIMARY KEY ("id")
);
CREATE TABLE "funcionarios" (
	"id" serial NOT NULL,
	"empresaId" integer NOT NULL,
	"nome" varchar(255) NOT NULL,
	"cpf" varchar(14),
	"rg" varchar(20),
	"telefone" varchar(20),
	"email" varchar(320),
	"funcao" text NOT NULL,
	"tipoContrato" text NOT NULL,
	"salario" decimal(10,2),
	"dataAdmissao" date,
	"dataDemissao" date,
	"valorDiaria" decimal(10,2),
	"valorMensal" decimal(10,2),
	"tipoCobranca" text,
	"dataInicioContrato" date,
	"dataFimContrato" date,
	"diaPagamento" integer,
	"cnh" varchar(20),
	"categoriaCnh" varchar(5),
	"vencimentoCnh" date,
	"mopp" boolean DEFAULT FALSE,
	"vencimentoMopp" date,
	"vencimentoAso" date,
	"banco" varchar(100),
	"agencia" varchar(10),
	"conta" varchar(20),
	"tipoConta" text,
	"chavePix" varchar(255),
	"observacoes" text,
	"foto" text,
	"ativo" boolean NOT NULL DEFAULT TRUE,
	"createdAt" timestamptz NOT NULL DEFAULT NOW(),
	"updatedAt" timestamptz NOT NULL DEFAULT NOW(),
	"deletedAt" timestamptz,
	"deletedBy" integer,
	"deleteReason" text,
	CONSTRAINT "funcionarios_id" PRIMARY KEY ("id")
);
CREATE TABLE "manutencoes" (
	"id" serial NOT NULL,
	"empresaId" integer NOT NULL,
	"veiculoId" integer NOT NULL,
	"data" date NOT NULL,
	"tipo" text NOT NULL,
	"descricao" text NOT NULL,
	"empresa" varchar(255),
	"valor" decimal(10,2),
	"kmAtual" integer,
	"proximaManutencaoKm" integer,
	"proximaManutencaoData" date,
	"notaFiscal" varchar(50),
	"observacoes" text,
	"createdAt" timestamptz NOT NULL DEFAULT NOW(),
	"updatedAt" timestamptz NOT NULL DEFAULT NOW(),
	"deletedAt" timestamptz,
	"deletedBy" integer,
	"deleteReason" text,
	CONSTRAINT "manutencoes_id" PRIMARY KEY ("id")
);
CREATE TABLE "users" (
	"id" serial NOT NULL,
	"openId" varchar(64) NOT NULL,
	"name" text,
	"email" varchar(320),
	"loginMethod" varchar(64),
	"role" text NOT NULL DEFAULT 'user',
	"createdAt" timestamptz NOT NULL DEFAULT NOW(),
	"updatedAt" timestamptz NOT NULL DEFAULT NOW(),
	"lastSignedIn" timestamptz NOT NULL DEFAULT NOW(),
	CONSTRAINT "users_id" PRIMARY KEY ("id"),
	CONSTRAINT "users_openId_unique" UNIQUE ("openId")
);
CREATE TABLE "veiculos" (
	"id" serial NOT NULL,
	"empresaId" integer NOT NULL,
	"placa" varchar(10) NOT NULL,
	"tipo" text NOT NULL,
	"cavaloPrincipalId" integer,
	"marca" varchar(100),
	"modelo" varchar(100),
	"ano" integer,
	"cor" varchar(50),
	"renavam" varchar(20),
	"chassi" varchar(30),
	"capacidadeCarga" decimal(8,2),
	"motoristaId" integer,
	"ajudanteId" integer,
	"kmAtual" integer,
	"mediaConsumo" decimal(5,2),
	"vencimentoCrlv" date,
	"vencimentoSeguro" date,
	"classificacao" integer DEFAULT 0,
	"observacoes" text,
	"ativo" boolean NOT NULL DEFAULT TRUE,
	"createdAt" timestamptz NOT NULL DEFAULT NOW(),
	"updatedAt" timestamptz NOT NULL DEFAULT NOW(),
	"deletedAt" timestamptz,
	"deletedBy" integer,
	"deleteReason" text,
	CONSTRAINT "veiculos_id" PRIMARY KEY ("id")
);
CREATE TABLE "viagens" (
	"id" serial NOT NULL,
	"empresaId" integer NOT NULL,
	"veiculoId" integer NOT NULL,
	"cavaloPrincipalId" integer,
	"motoristaId" integer,
	"ajudante1Id" integer,
	"ajudante2Id" integer,
	"ajudante3Id" integer,
	"origem" varchar(255),
	"destino" varchar(255),
	"dataSaida" timestamptz,
	"dataChegada" timestamptz,
	"kmSaida" integer,
	"kmChegada" integer,
	"kmRodado" integer,
	"descricaoCarga" text,
	"pesoCarga" decimal(8,2),
	"freteTotalIda" decimal(10,2),
	"freteTotalVolta" decimal(10,2),
	"freteTotal" decimal(10,2),
	"adiantamento" decimal(10,2),
	"saldoViagem" decimal(10,2),
	"totalDespesas" decimal(10,2),
	"mediaConsumo" decimal(5,2),
	"status" text NOT NULL DEFAULT 'planejada',
	"observacoes" text,
	"createdAt" timestamptz NOT NULL DEFAULT NOW(),
	"updatedAt" timestamptz NOT NULL DEFAULT NOW(),
	"deletedAt" timestamptz,
	"deletedBy" integer,
	"deleteReason" text,
	CONSTRAINT "viagens_id" PRIMARY KEY ("id")
);
