export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  aiProvider: process.env.AI_PROVIDER ?? "",
  openaiApiKey: process.env.OPENAI_API_KEY ?? "",
  openaiApiUrl: process.env.OPENAI_API_URL ?? "",
  openaiModel: process.env.OPENAI_MODEL ?? "",
  geminiApiKey: process.env.GEMINI_API_KEY ?? process.env.GOOGLE_API_KEY ?? "",
  geminiModel: process.env.GEMINI_MODEL ?? "",
  azureOpenaiApiKey: process.env.AZURE_OPENAI_API_KEY ?? "",
  azureOpenaiEndpoint: process.env.AZURE_OPENAI_ENDPOINT ?? "",
  azureOpenaiDeployment: process.env.AZURE_OPENAI_DEPLOYMENT ?? "",
  azureOpenaiApiVersion: process.env.AZURE_OPENAI_API_VERSION ?? "",
  localAiUrl: process.env.LOCAL_AI_URL ?? "",
  localAiModel: process.env.LOCAL_AI_MODEL ?? "",
};
